### ISSUE TITLE
Code review and readme for Whippet base theme

### ISSUE THREAD

**Issue by harry-m** [dxw/whippet#10]
It's just a roadmap at the moment. It needs love.

Question: should we use the GovSite as the base theme? If not, should we fork it? Many of the improvements made there will probably apply to the base theme too. @lilydartdev

**Comment by lilydartdev** [comment]
No, GovSite is already using the base theme so without it's styling it doesn't have much purpose.

We just need to transfer back any improvements that we made. Forking it would be fine.

**Comment by harry-m** [comment]
Do you have time to do that? And/or start a readme? It's here: https://github.com/dxw/whippet-theme-template

**Comment by lilydartdev** [comment]
Not this week, maybe next week, might be better to get Magda to look at it.

**Comment by tomdxw** [comment]
Not sure exactly what needed doing, but whippet-theme-template is now being used so I presume this is okay to close.
