### ISSUE TITLE
Apache wordpress.conf rules ignored with a sub-directory multisite

### ISSUE THREAD

**Issue by tommarshall** [dxw/whippet#107]
I'm trying to use `whipper server` on a sub-directory multisite project, however I'm experiencing issues with the sites on the sub-directories.

I can see [the multisite Apache config](https://github.com/dxw/whippet/blob/master/docker-images/whippet-wordpress/wordpress.conf) in `/etc/apache2/sites-enabled/wordpress.conf` within the Docker container, but it's behaving as if those rules are being ignored, e.g. I'm getting 404s for the theme assets at http://example.local/some-site/wp-content/themes/example/css/foo.css, but http://example.local/wp-content/themes/example/css/foo.css returns a 200 correctly.

If I create a syntax error within `/etc/apache2/sites-enabled/wordpress.conf` via `whippet server console` and reload apache it fails. So the file is definitely loaded, but it does appear the rules are being ignored.

I have the following in my `config/server-local.php`:

```
<?php
define('WP_SITEURL', 'http://example.local');
define('WP_HOME', 'http://example.local');
define('WP_ALLOW_MULTISITE', true);
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', false);
define('DOMAIN_CURRENT_SITE', 'example.local');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);
```

Any ideas?

**Comment by tommarshall** [comment]
Changing:
```
<Directory />
```
To:
```
<Directory /var/www/html/>
```
in `/etc/apache2/sites-enabled/wordpress.conf` via `whippet server console` and reloading apache seems to resolve the issue, though I'm not currently sure why.

[The apache docs](http://httpd.apache.org/docs/current/mod/core.html#directory) state that parent directory config is included, i.e. `<Directory />` will apply to all directories, though it is the first ruleset applied, so can be overridden by children, e.g. `<Directory /var/>`, but I can't find anything in the apache conf on the container that appears to be overriding the rewrite rules.

**Comment by Stretch96** [comment]
It appears that the `<directory />` directive in the site config (in `sites-enabled/wordpress.conf`) is being ignored, possibly because `<directory />` has already been defined, in `apache.conf`, or that it is being loaded after the `default` virtual host.

I'll create a PR that puts the configuration into the `default` virtualhost (or removes the default virtual host, and change `wordpress.conf` to a virtual host)
