### ISSUE TITLE
Add a Vagrantfile for ease of use and Windows support

### ISSUE THREAD

**Issue by harry-m** [dxw/whippet#11]
I don't think we should natively support Windows, but we could provide a Vagrant file that we maintain so that Windows users (as well as everyone else) can use that.

Many of the tools we are using as dependencies will either not work on Windows, will work incompatibly, or will be a pain to set up.

Thoughts?

**Comment by lilydartdev** [comment]
Vagrant is the answer. We can't meaningfully support Windows because we can't dogfood it.

**Comment by tomdxw** [comment]
Or we could add to the README some text to the effect of "we don't know if this works on Windows, but you're welcome to try and we'll merge any patches that don't break Linux or OSX".

**Comment by harry-m** [comment]
I think I'm with Lily. Vagrant makes the problem go away.

TODO: Make a Vagrantfile, test it, add a section to the Readme

**Comment by tomdxw** [comment]
@harry-m Is this still something we want to do?

I checked and Travis can run tests on Linux and OSX, but not Windows unfortunately.

I don't know too much about Vagrant. I could make a `Dockerfile` pretty easily which should make it possible to run it on Windows if the user has Docker Toolbox installed.

**Comment by harry-m** [comment]
No, I think this is not that important. 

Happy to revisit if we get requests for it.
