### ISSUE TITLE
https://github.com/dxw/whippet-theme-template.git is private

### ISSUE THREAD

**Issue by tomdxw** [dxw/whippet#13]
Anybody outside of dxw cannot checkout all the submodules as one is private.

**Comment by harry-m** [comment]
Ah yes balls. I'll deal.

**Comment by kaelig** [comment]
I believe I encountered this issue today, any update on when it will be available publically?

Here is my console output:

```
git submodule update --init --recursive
Submodule 'generators/theme/template' (https://github.com/dxw/whippet-theme-template.git) registered for path 'generators/theme/template'
Submodule 'lib/rubbish_thor_clone' (https://github.com/dxw/RubbishThorClone.git) registered for path 'lib/rubbish_thor_clone'
Cloning into 'generators/theme/template'...
remote: Repository not found.
fatal: repository 'https://github.com/dxw/whippet-theme-template.git/' not found
Clone of 'https://github.com/dxw/whippet-theme-template.git' into submodule path 'generators/theme/template' failed
```

**Comment by harry-m** [comment]
Hi Kaelig - sorry for the bother. The reason it's private is that it's still quite unfinished and needs quite a bit of work. I've added you as a collaborator so you can have a look!

**Comment by kaelig** [comment]
Thank you very much @harry-m, it works with the collaborator access.

**Comment by harry-m** [comment]
Cool. I'll leave this open until we've fixed it.

**Comment by tomdxw** [comment]
@harry-m Looks like you made /dxw/whippet-theme-template public. Are we okay to close this one now?

**Comment by harry-m** [comment]
Yup
