### ISSUE TITLE
Remove `whippet theme watch` command

### ISSUE THREAD

**Issue by mallorydxw** [dxw/whippet#140]
We don't actually put `Gruntfile.js` etc in the `vendor` directory of themes, and being a thin wrapper around `grunt watch` isn't actually that useful.

**Comment by snim2** [comment]
This has already been removed, so closing:

```shell
❯ whippet theme -h
Subcommands:

 theme  grunt  *arguments      Runs the specified grunt command in the context of your theme
 theme  help   COMMAND         get help on a COMMAND
```
