### ISSUE TITLE
"whippet plugins upgrade my-plugin" modifies git hashes of other plugins

### ISSUE THREAD

**Issue by tomdxw** [dxw/whippet#15]
1. git clone ... my-app && cd my-app
2. whippet plugins install
3. cd wp-content/plugins/plugin1 && git checkout HEAD^ && cd -
4. whippet plugins upgrade plugin2

Expected behaviour:

In `plugins.lock`: You upgraded plugin2 to the latest version.

Actual behaviour:

In `plugins.lock`: You upgraded plugin2 to the latest version and you downgraded plugin1 to an older version.

**Comment by dgmstuart** [comment]
Isn't this a pathological case? (Deliberately moving a plugin out of sync with the lockfile) - Is there a realistic scenario? Presumably devs should only ever be interacting with plugins through whippet (?)

I feel like the expected behaviour might reasonably be for the lockfile to reinstall the specified version of the other plugin (in what you describe it's the opposite: updated itself to match the reality in the directory, right?) But what you describe is cool too.

**Comment by tomdxw** [comment]
Not pathological at all. You may be checking out an older version of a plugin to debug an issue. That's a pretty common occurrence.

But here's a much more common situation (I didn't use it above because if you actually wanted to reproduce it on demand you'd have to clone the repo elsewhere and do some pushing).

1. git clone ... my-app && cd my-app
2. whippet plugins install
3. Some time passes
4. git pull --ff-only
5. whippet plugins upgrade plugin2
6. git commit -am 'Update plugin2'

Here the developer has cloned an app repo and installed the plugins. And then some time later they've pulled a change to plugins.lock but they haven't run "whippet plugins install" (I certainly don't run that every time I pull - it takes far too long to run on every pull). Then they try to upgrade a plugin only to accidentally revert all the other plugins.

**Comment by harry-m** [comment]
I think this is pathological.

The right thing to do here is to make it quicker to update and more obvious when updates are in plugins.lock that are not on disk. Like, in rails, when I pull and there are new gems, the app generally won't run until running bundle, and that is not onerous.

That whippet enforces on disk the stuff which is in plugins.lock is deliberate - I don't think we should stop doing that.

**Comment by dgmstuart** [comment]
> You may be checking out an older version of a plugin to debug an issue.

Wouldn't the 'whippet way' to do that be to edit the plugin manifest?

> The right thing to do here is to make it quicker to update and more obvious when updates are in plugins.lock that are not on disk. Like, in rails, when I pull and there are new gems, the app generally won't run until running bundle, and that is not onerous.

That feels right to me. If you're not using the plugin versions specified in the lockfile, you're not looking at the same app as the person who committed that lockfile. 

I think this might be more obvious when we have tests: if a test assumes a specific version of a plugin then your tests would fail unless the installed plugins match the lockfile.

**Comment by tomdxw** [comment]
I've found another example in the wild. The commit message is:

    GA plugin update 5.3.3

If you look at plugins.lock it shows that Google Analytics by Yoast has been updated to 5.3.3 and seven other plugins have been downgraded to older versions.

> Like, in rails, when I pull and there are new gems, the app generally won't run until running bundle, and that is not onerous.

I'm not sure how we can do that with whippet? You could prevent "whippet server start" from running until the plugins have been updated, but if you run "whippet server start && git pull --ff-only", how can whippet detect that the plugins aren't at the correct commits and stop? More importantly - if whippet server *does* stop when a commit hash changes, how are we going to temporarily check out other versions of plugins for testing? Will we have to check out the other version, update plugins.lock, and re-run "whippet server start"? That seems pretty tedious.

In this case it was a routine plugin upgrade - I wouldn't be surprised if the person doing this didn't even test it locally before pushing to staging (so there's no way whippet could have prevented that other than by changing how the whippet plugins install/upgrade commands work).

**Comment by dgmstuart** [comment]
Confused. Is this another scenario where it looks like either the lockfile wasn't committed, or the manifest file was updated without running plugins install/upgrade? 

If so then I still think the approach should be for something to complain loudly and immediately when that happens: the risk is that different devs will end up developing against significantly different versions of plugins which == pain.

**Comment by dgmstuart** [comment]
Though actually I think the current functionality isn't correct: 

https://github.com/dxw/whippet/blob/2444e35cba474b7a3b9b0dcd279f38eb4078c4d9/lib/modules/helpers/manifest_io.trait.php#L118-L129

```php
      $git = new Git("{$this->plugin_dir}/{$dir}");

     // ...

      $this->plugins_locked->$dir              = new stdClass();
      $this->plugins_locked->$dir->repository  = $this->plugins_manifest->$dir->repository;
      $this->plugins_locked->$dir->revision    = $this->plugins_manifest->$dir->revision;
      $this->plugins_locked->$dir->commit      = $commit;
```

I think this says "get the commit hash from whatever version is currently installed and set the lockfile to that version"

This makes sense only if it's only ever run in a state where:

  * all the installed plugins match the commits specified in the current version of the lockfile...
  * ...except any plugins which were upgraded with `whippet plugin upgrade` 

It looks like we can't assume that.

I suggest that the first thing the upgrade action should do is to check whether the commit hashes of the plugins on disk match the hashes in the plugins.lock, and blow up if they don't. Blowing up here is appropriate since 

1. You probably shouldn't be doing an upgrade unless all your plugins are in sync
2. It's not clear which is correct: the lockfile, or the files on disk.

Currently the code assumes that the files on disk are always correct, and silently overrides the lockfile, which I think will be wrong in the majority of cases.

**Comment by harry-m** [comment]
You're right about those assumptions, but I'm not sure I agree that we can't assume that? Either way, I agree that something should check the installed commits, but that it should prob do it whenever whippet runs (not just on install or upgrade).

I think I still feel like this situation has arisen from user error though! If you were to install a gem in a ruby project and then manually change that gem's source files without running bundle, I suspect similar shit things would happen?

**Comment by harry-m** [comment]
Is there anything we can do to understand how often this issue actually bites someone?

I think a mechanism to alert people that ```whippet plugins install``` needs to be run is the right idea, but not sure how to do that. And not sure how high priority this is.

We can certainly add something to whippet-server to check this, but that won't help everyone. Perhaps a better idea would be to add something to git to look for changes to plugins.lock and automatically run Whippet, or print a warning? Something that we could add when ```whippet init``` is run?

**Comment by tomdxw** [comment]
> We can certainly add something to whippet-server to check this, but that won't help everyone.

Until everyone is using whippet server, that is. Once all the bugs are fixed, there's no reason everybody can't use it.

> Perhaps a better idea would be to add something to git to look for changes to plugins.lock and automatically run Whippet, or print a warning? Something that we could add when `whippet init` is run?

`whippet plugins install` takes a very very long time - I'm not going to wait 2 minutes between typing `git commit` and typing my commit message. Also, git hooks are not part of the repository - they're specific to one particular clone of the repository. So if you create a project with `whippet init`, when I clone it I won't have the same hooks as you.

**Comment by harry-m** [comment]
Does it need to actually run ```whippet plugins install``` though? I think it just needs to check:

- Each plugin's current commit against lockfile commit
- Lockfile list against plugins list

And warn you if they differ?

Pity about the git hooks.

We could perhaps add the check to any invocation of the whippet command from a project directory, and go from there? Then when whippet server is merged in, it will work for that too.

**Comment by tomdxw** [comment]
> We could perhaps add the check to any invocation of the whippet command from a project directory, and go from there?

Yeah, that sounds good.

**Comment by dgmstuart** [comment]
@tomdxw we can't have git hooks locally, but can we have them on Travis, right? If blowing up locally is hard, then doing it on CI feels like a good solution.

**Comment by tomdxw** [comment]
@dgmstuart The issue here is that the plugins in a user's clone of a repository might differ from the plugins in the `plugins.lock` file. So unfortunately Travis can't help us with this one.

**Comment by tomdxw** [comment]
The `plugins` module is now deprecated. Closing.
