### ISSUE TITLE
Moving from git submodule to plugins failed

### ISSUE THREAD

**Issue by gwire** [dxw/whippet#2]
(Apologies for lack of detail, this occurred a couple of weeks ago.)\

A site had a (forked) plugin in wp-content/plugins/foo .

The plugin was modified upstream, meaning we no longer needed to use the forked version.

I removed the submodule (from .gitmodules) and added it to the plugins file.  Ran "whippet plugins install" which successfully added it. Committed the changes, including plugins.lock . Pushed to the deployment branch.

On deployment on the server the deployed a new release with the correct identifier, but the plugin was still the forked version.

I needed to manually wipe references to the old repo from the deployment working directory in order to get the repo switch to work.

**Comment by tomdxw** [comment]
On a site I was working on today we had a plugin in the git repo which I replaced with a submodule. Of all the files which should have been there, only .git (the flat file with a gitdir reference), lib/ui.php, and vendor.phar had been copied into the release.

**Comment by tomdxw** [comment]
#34 may resolve this issue.

**Comment by snim2** [comment]
We no longer use Git submodules for plugin management, so if this bug still exists, hopefully we won't trigger it. Therefore, closing.
