### ISSUE TITLE
Don't accept # as a comment in plugins file

### ISSUE THREAD

**Issue by harry-m** [dxw/whippet#27]
\# is deprecated as a comment in PHP's ini handling. Let's add a check in Whippet so that if people use it by mistake (instead of ;) they get an error straight away, instead of later when they're deploying, or doing some other more important thing.

---

Ticket: https://dxw.zendesk.com/agent/tickets/4913

- [x] Add phpunit
- [x] Add .travis.yml
- [x] Write a failing test (may require shelling out)
- [x] Make it pass
- [x] Search for #-comments in other files (i.e. README, example files, etc)

**Comment by tomdxw** [comment]
Note that there are comments in `plugins` files in the README. I'll address those too.

**Comment by tomdxw** [comment]
Started work on this: https://github.com/dxw/whippet/tree/feature/disallow-hash-comments

**Comment by tomdxw** [comment]
I want to fix the tests so that they'll work without network access. See feature/disallow-hash-comments-stash where I started on that.

**Comment by tomdxw** [comment]
Interesting. This bug only affects 5.x. 7.0 doesn't complain. This appears to contradict the documentation.

```
core@workshop /workbench/src 
% docker run -ti --rm php:5.6 sh -c 'echo "# 123" > /t && php -r "error_reporting(E_ALL); var_dump(parse_ini_file(\"/t\"));"'

Deprecated: Comments starting with '#' are deprecated in /t on line 1 in Command line code on line 1
array(0) {
}
✔ 

core@workshop /workbench/src 
% docker run -ti --rm php:7.0 sh -c 'echo "# 123" > /t && php -r "error_reporting(E_ALL); var_dump(parse_ini_file(\"/t\"));"'
array(0) {
}
✔ 
```

**Comment by tomdxw** [comment]
Anyway, #31 is merged so I think this is okay to close.
