### ISSUE TITLE
Unsafe failure mode for whippet deploy

### ISSUE THREAD

**Issue by harry-m** [dxw/whippet#30]
1) if the uploads directory points at an unmounted disk, whippet deploy will fail
2) this is even if the deploy is up to date already
3) the deploy directory will be DEPLOY.broken
4) under some circumstance this will result in current pointing to a non-existent directory
 (previously good deploy being renamed to .broken and symlink not updating?)
 (directory filling wil .broken deploys and last-good-current getting deleted?)

**Comment by Stretch96** [comment]
Pull request: https://github.com/dxw/whippet/pull/33

**Comment by tomdxw** [comment]
#33 was merged so this must be fixed.
