### ISSUE TITLE
whippet deploy is slower

### ISSUE THREAD

**Issue by mallorydxw** [dxw/whippet#40]
Since #37, `whippet deploy` runs about 90 seconds slower than before. This is likely due to using pure PHP in place of `system('cp -r ...')`/`system('cp -a ...')`.

I wonder if there's a better native implementation available.

**Comment by harry-m** [comment]
Chris, can you pick this one up when you're able?

**Comment by Stretch96** [comment]
The PHP `copy()` runs on average 25% slower than `system('copy ')` which is unfortunate … The only other thing I can think of that may help, is using the `RecursiveDirectoryIterator`, instead of the function recursively calling itself. I’ll put something together, and see if it runs any faster.
