### ISSUE TITLE
Config files (discussion)

### ISSUE THREAD

**Issue by tomdxw** [dxw/whippet#6]
The config files could use some improvement. We have plugins and plugins.lock for managing plugins and config/application.json for selecting the WordPress version. Also, the whole plugins installation process assumes the developer has a set of plugins stored in git repos in regularly-named locations (i.e. git@git.dxw.net:wordpress-plugins/*). That means when we publish whippet, the "plugins install" and "deploy" commands will only ever be used by us.

I think at the very least we should aim to:

1. Make it possible to install plugins from some other system (i.e. directly from wordpress.org using the API) so that non-dxw people have some way of using whippet
2. Merge the config/application.json and plugins into one config file

Here's something to get the discussion started: https://github.com/roots/bedrock/blob/master/composer.json

**Comment by harry-m** [comment]
Hmm. On number 1: there is git@git.dxw.net:wordpress-plugins/, which I have added to the readme. Though I have not used it in practice so not sure about consistency of tagging or updates etc. We can make our own mirror if required. I wanted to keep using git as the mechanism for managing code - I think it's neat. And it means we don't _have_ to rely on WP.org's version info, which is often strange. I also think it makes sense to keep plugins separate from other configuration, a la a gemfile.

On 2, I did start out with WP version in the plugins file. But I took it out again. (I'm afraid I don't remember why, but the commit history might say). In any case, I think application.json will soon have more stuff in it. I'd like to have a conversation about how themes should work in Whippet - my suspicion is that Whippet should only care about one main theme which is defined as the "application" theme in that file - and which Whippet will take care of activating, and will test. Other themes could then be added but wouldn't have stuff happen to them automagically. Not sure about that bit yet.

What do you think?

**Comment by tomdxw** [comment]
> which I have added to the readme. 

Oh, I didn't realise that wp-plugins user/organisation existed. Yeah, that would work.

> I also think it makes sense to keep plugins separate from other configuration, a la a gemfile.

The way I look at it is that WordPress is just another dependency that needs to be cloned. In that sense it's no different from plugins. It just needs to be put in a different location to the plugins when deploying.

> my suspicion is that Whippet should only care about one main theme which is defined as the "application" theme in that file - and which Whippet will take care of activating, and will test.

Sounds like that would work well with a lot of our sites, but many do have different themes on different subsites. I would propose any test running happen to all themes in the wp-content/themes directory (if they have the appropriate files), and then have a "default theme" option so that when clients create subsites they don't default to using twentyfitteen and cause errors (IIRC default theme is just a constant).

**Comment by tomdxw** [comment]
As per discussion on #28, we'll close this for the moment. But when we add a config file for themes or languages, I'd like to think about moving everything into one file.
