### ISSUE TITLE
Notify via slack

### ISSUE THREAD

**Issue by mallorydxw** [dxw/whippet#72]
```
whippet deploy /site --notify-slack=https://slackhoook`
```

(This would use the default username, channel, etc. assigned to the slack hook. No need to override the defaults.)

Should notify three things:
- whippet deployment started
- whippet deployment finished successfully
- whippet deployment exited with errors (show the errors)

It should also include a link to the site (does whippet have that information? May need to be provided by a separate option if not).

**Comment by tomdxw** [comment]
Actually, should this be added to whippet? Wouldn't it be better to have chef do `whippet deploy ... && slack-notify https://dxw.slack.com/123`?

**Comment by snim2** [comment]
Internally we now have a different solution for tracking deployments in Slack, so closing.
