### ISSUE TITLE
Connecting to MySQL from outside

### ISSUE THREAD

**Issue by tomdxw** [dxw/whippet#89]
Currently if you need to connect to MySQL from outside the Docker for Mac VM, you need to run this command:

```
docker run -ti --rm -p 3306:3306 --link whippet_mysql:conn verb/socat tcp-listen:3306,reuseaddr,fork tcp:conn:3306
```

But should we expose port 3306 by default? (This may conflict with an existing MySQL server - maybe we should use another port? But if we use a different port then users will have to look it up every time)

**Comment by RobjS** [comment]
This relates to the deprecated `whippet server` module, so can be closed.
