### ISSUE TITLE
`whippet deploy` removes files from core causing `wp core verify-checksums` to fail

### ISSUE THREAD

**Issue by tommarshall** [dxw/whippet#98]
[`whippet deploy` is removing `readme.html` and `wp-config-sample.php`](https://github.com/dxw/whippet/blob/eff5e283d2a4c4630b153f0d8c23a6e92eea67e2/src/Modules/Release.php#L78).

This causes [`wp core verify-checksums`](https://wp-cli.org/commands/core/verify-checksums/) to fail:

```
$ wp core verify-checksums
Warning: File doesn't exist: readme.html
Warning: File doesn't exist: wp-config-sample.php
Error: WordPress install doesn't verify against checksums.
```

We have automated monitoring in place that periodically checks the integrity of our WordPress sites by running `wp core verify-checksums`. That automated check is currently reporting a false failure for Whippet sites.

I appreciate that this is primarily an internal tool for DXW's use, but given that these files are relatively harmless* and that there's security benefit to be had from being able to use `wp core verify-checksums` I wonder whether you'd consider changing this behaviour?

---

*`readme.html` leaks the core version, but we block `readme.html` at the web server level, as plugins can also contain README files that leak the version. Blocking at the web server gives us coverage for those as well.

**Comment by dgmstuart** [comment]
Hi Tom - thanks for the PR - I'll get one of our ops to look at this

**Comment by harry-m** [comment]
Yes, I think that's a really sensible check, and the version leak is a minor control and easy enough to implement elsewhere.

@dgmstuart are you happy to review and accept the PR? AndI'll pick up the conversation with ops.

**Comment by dgmstuart** [comment]
@harry-m I'm away till Tuesday and in any case I'd want to check that these files weren't deliberately deleted because of something to do with our platform. Have you discussed with ops? 

I don't think I'm the right person to review this ticket: I don't know anything at all about the deployment process.

**Comment by harry-m** [comment]
They weren't - we already block those files at network level anyway. Ops are happy. But perhaps @Stretch96 could pick this up anyway, if you're away!

**Comment by dgmstuart** [comment]
@harry-m FYI - You added the code to delete those files originally 😜 

https://github.com/dxw/whippet/commit/b299b33ba1f856dbc831392cdd51cbc09209f3cc#diff-cddbeecb4d8777058b0721863b17f96dR32

**Comment by tommarshall** [comment]
That's great. Thanks for accepting 😄
